### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tasn** [zaubererty/ember-cli-django-rest-auth#10]
Hey,

Please release a new version once #9 is in. There are already a few fixes that bring this plugin to the modern ember world, and unfortunately no releases to accompany them. Please make a release.

Thanks,
Tom.

**Comment by zaubererty** [comment]
I'll consider to release a new version, can you check the suggested code clean up ( #8 ) ?

**Comment by tasn** [comment]
I will check, though I think that's orthogonal to the new release. At the moment I'm forced to use versions from Git in my projects because I'm using ESA 1.0 and Ember 2. I'm sure I'm not the only one, and I think a release will be beneficial for everyone.

The clean-up is a good idea regardless, but not a requirement.

**Comment by zaubererty** [comment]
Release of 0.5.0 is done

**Comment by tasn** [comment]
Thanks for being so quick about everything.
